<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseIISExpress>true</UseIISExpress>
    <UseGlobalApplicationHostFile />
    <ProjectTypeGuids>{349c5851-65df-11da-9384-00065b846f21};{fae04ec0-301f-11d3-bf4b-00c04f79efbc}</ProjectTypeGuids>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.WorkSpaces" Version="3.7.300.39" />
    <PackageReference Include="AWSSDK.DirectoryService" Version="3.7.300.39" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Web" />
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>

</Project>